language: python

python: "3.7"

before_install:
  - sudo apt-get install -y python3-dev libasound2-dev
install:
  - pip3 install coverage
  - pip3 install -r requirements.txt

script: coverage run -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)
