language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest tests/ # or py.test for Python versions 3.5 and below

notifications:
  webhooks:
    - http://itera.requestcatcher.com/
    - https://webhook.site/ef9657a4-e1e0-4932-b144-41b5b127012e
