language: python
python:
  - "2.6"
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
#  - pytest # or py.test for Python versions 3.5 and below

notifications:
  webhooks:
    - http://itera.requestcatcher.com/
    - https://webhook.site/#/ef9657a4-e1e0-4932-b144-41b5b127012e/135c3c36-cb41-41c4-957d-4b4791cccf5c/0
